sudo: required
dist: trusty
group: deprecated-2017Q2

services:
 - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y nodejs jq

install:
  - npm install -g dockerfile_lint

before_script:
  - mkdir $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - tmp=`mktemp`
  - echo '{"insecure-registries":["172.30.0.0/16"]}' > ${tmp}
  - sudo mv ${tmp} /etc/docker/daemon.json
  - sudo mount --make-shared /
  - sudo service docker restart
  - make lint

script:
  - make
  - make test
  - wget `curl -s https://api.github.com/repos/openshift/origin/releases/latest | jq -r ".assets[] | select(.name | test(\"linux-64bit\")) | .browser_download_url" | grep -i client-tools`
  - tar xvfz `ls openshift-origin-client-tools-*.tar.gz` --strip-components=1 -C $HOME/bin
  - oc cluster up
  - export OC_USER=`oc whoami` OC_PASS=`oc whoami -t`
  - oc login -u system:admin
  - oc rollout status -w dc/docker-registry -n default || oc rollout retry dc/docker-registry -n default && oc rollout status -w dc/docker-registry -n default
  - export REGISTRY_IP=`oc get svc/docker-registry -o json -n default | jq -r '.spec.clusterIP'`
  - make openshift-test REGISTRY=${REGISTRY_IP} OC_USER=${OC_USER} OC_PASS=${OC_PASS}
  - oc version
