MAINTAINER Dinko Korunic <dkorunic@haproxy.com>

LABEL name="haproxytech/haproxy" \\
      vendor="HAProxy" \\
      version="1.8.20" \\
      release="1" \\
      url="https://www.haproxy.org" \\
      summary="HAProxy OpenSource" \\
      description="HAProxy OSS" \\
      run='docker run -tdi --name ${NAME} ${IMAGE}' \\
      io.k8s.description="HAProxy OpenSource" \\
      io.k8s.display-name="HAProxy OSS" \\
      io.openshift.expose-services="8080/tcp:http,8443/tcp:https" \\
      io.openshift.tags="http,https,proxy,loadbalancer"

ENV HAPROXY_BRANCH 1.8
ENV HAPROXY_MINOR 1.8.20
ENV HAPROXY_MD5 abf9b7b1aa84e0839501e006fc20d7fd
ENV HAPROXY_SRC_URL "http://www.haproxy.org/download"

ENV HAPROXY_UID 10001
