MAINTAINER Dinko Korunic <dkorunic@haproxy.com>

LABEL name="haproxytech/haproxy" \\
      vendor="HAProxy" \\
      version="1.9.16" \\
      release="1" \\
      url="https://www.haproxy.org" \\
      summary="HAProxy OpenSource" \\
      description="HAProxy OSS" \\
      run='docker run -tdi --name ${NAME} ${IMAGE}' \\
      io.k8s.description="HAProxy OpenSource" \\
      io.k8s.display-name="HAProxy OSS" \\
      io.openshift.expose-services="8080/tcp:http,8443/tcp:https" \\
      io.openshift.tags="http,https,proxy,loadbalancer"

ENV HAPROXY_BRANCH 1.9
ENV HAPROXY_MINOR 1.9.16
ENV HAPROXY_MD5 a81cd10d995cb9cd384052702cacb81e
ENV HAPROXY_SRC_URL "http://www.haproxy.org/download"

ENV HAPROXY_UID 10001
